let head1 = document.querySelector('.head1')
let head2 = document.querySelector('.head2')
let head3 = document.querySelector('.head3')
let head4 = document.querySelector('.head4')
let head5 = document.querySelector('.head5')
let head6 = document.querySelector('.head6')


let ulItem =document.getElementById('ulItem')
let listItem =document.getElementsByClassName('listItem')
let textList = document.getElementById('text-list')
// console.log(head1.parentNode)
// console.log(head3.parentNode)
// alert(head5.parentNode)
// console.log(head3.parentNode)
// console.log(head2.parentElement)
// console.log(head6.parentElement)
// console.log(head2.previousElementSibling)
// console.log(head3.previousElementSibling.previousElementSibling)
// console.log(head2.nextElementSibling)
// console.log(head2.nextElementSibling.nextElementSibling)
// console.log(listItem[1].nextSibling.nextSibling)
// console.log(ulItem.childElementCount)

// console.log(ulItem.childElementCount
// console.log(ulItem.children)
// console.log(ulItem.children[4])
// console.log(ulItem.childNodes )
// console.log(ulItem.hasChildNodes())
// console.log(textList.hasChildNodes())
// console.log(ulItem.firstChild)
// console.log(ulItem.lastChild)
console.log(ulItem.firstElementChild)
console.log(ulItem.lastElementChild.firstElementChild.style.color = 'red')